name: Issue → Grant Access PR

on:
  issues:
    types: [opened]

jobs:
  handle-grant:
    runs-on: ubuntu-latest  
    steps:
    - name: Set up Git to authenticate with token
      run: |
        git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com/BrunoKings0/".insteadOf "https://github.com/BrunoKings0/"

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Checkout dev branch
      run: |
        git fetch origin dev:dev
        git checkout dev
        git pull origin dev

    - name: Configure python
      uses: actions/setup-python@v6
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-hcl2==7.3.1

    - name: Parse issue data
      id: parse
      env:
        ISSUE_BODY: ${{ github.event.issue.body }}
      run: |
        AwsTeam=$(echo "$ISSUE_BODY" | grep -E '^AwsTeam:' | sed -E 's/^AwsTeam:[[:space:]]*//')
        echo "AwsTeam='$AwsTeam'"

        personal=$(echo "$ISSUE_BODY" | grep -Po 'Personal:\s*\[\K[^\]]+' || echo "")
        confidential=$(echo "$ISSUE_BODY" | grep -Po 'Confidential:\s*\[\K[^\]]+' || echo "")
        strictly=$(echo "$ISSUE_BODY" | grep -Po 'Strictly Confidential:\s*\[\K[^\]]+' || echo "")

        echo "Personal='$personal'"
        echo "Confidential='$confidential'"
        echo "Strictly='$strictly'"

        echo "aws_team=$AwsTeam" >> $GITHUB_OUTPUT
        echo "personal_list=$personal" >> $GITHUB_OUTPUT
        echo "confidential_list=$confidential" >> $GITHUB_OUTPUT
        echo "strictly_list=$strictly" >> $GITHUB_OUTPUT

    - name: Prepare branch
      id: branch
      run: |
        AWS_TEAM="${{ steps.parse.outputs.aws_team }}"
        PR_BRANCH="grant-${AWS_TEAM}-${{ github.event.issue.number }}"
        echo "branch=$PR_BRANCH" >> $GITHUB_OUTPUT
        git checkout -b "$PR_BRANCH"
